### ISSUE TITLE
How should exceptions be handled (in general, not just in iterate)?

### ISSUE THREAD

**Issue by shaug** [staltz/callbag-iterate#1]
https://github.com/staltz/callbag-iterate/blob/df42e93396d91952079b929e940e1a23e0ead266/index.js#L5

Perhaps this is an issue for the broader spec or the getting-started doc, but what should be the 'best practice' for handling exceptions in operations? For example, a basic `tap` implementation could look like the following:

```javascript
const tap = operation => source => (start, sink) => {
  if (start !== 0) return;
  source(0, (t, d) => {
    if (t === 1) operation(d);
    sink(t, d);
  });
}
```

But in the face of `operation` throwing an exception, what should a 'well-behaved' callbag operation/puller/observable do? 

```javascript
if (t === 1) {
  try {
    operation(d);
  } catch (err) {
    // is this best practice?
    source(2, err);
    sink(2, err);
    // should err be re-thrown?
  }
}
```

**Comment by staltz** [comment]
The try/catch from your last snippet is a good approach, in my opinion. So far I have chosen to just let the whole thing crash in case an error happens in `operation`, but that's just my choice. I prefer to reserve `fn(2, err)` for `err` that are indeterministic, like errors from network requests, because only then does it make sense to apply a `retry` or something like that. But feel free to use the try/catch around `operation(d)`.

And I think it's also good to send `(2, err)` to both source and sink. Just sending `source(2)` and `sink(2)` would be enough for the purpose of disposing resources in both of them, but in case they handle errors, it's polite to give the reason `data=err` for `type=2` messages.
